# Generated by Django 4.0 on 2022-05-12 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_cartorderitems_rename_cartmodel_cartorder_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartorderitems',
            options={'verbose_name_plural': 'CartOrderItems'},
        ),
    ]
